services:
  - type: web
    name: little-lemon-backend
    env: node
    plan: free
    rootDir: little-lemon-backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://LittleLemonAdmin:kylo2014@cluster0.xan2btq.mongodb.net/MiEmpresa?retryWrites=true&w=majority
